# theme: jekyll-theme-slate
# theme: minimal-mistakes-jekyll
#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
title: ""
description: ""
author: Steven Wu
email: stevenhwu@gmail.com
layout: page
fixed_navbar: top
hide_footer: true
# hero_height: is-small
plugins:
- github-pages
# footer_menu: footer_menu
